Release 367.57-0ubuntu5
Sync with the archive.

diff --git a/debian/templates/nvidia-graphics-drivers.postinst.in b/debian/templates/nvidia-graphics-drivers.postinst.in
--- a/debian/templates/nvidia-graphics-drivers.postinst.in
+++ b/debian/templates/nvidia-graphics-drivers.postinst.in
@@ -39,6 +39,7 @@ _is_kernel_name_correct() {
     KERNEL_NAME=$1
     
     for kernel in /boot/config-*; do
+        [ -f "$kernel" ] || continue
         KERNEL=${kernel#*-}
         if [ "${KERNEL}" = "${KERNEL_NAME}" ]; then
             CORRECT="yes"
@@ -58,6 +59,7 @@ _get_newest_kernel_debian() {
     NEWEST_ABI=
     
     for kernel in /boot/config-*; do
+        [ -f "$kernel" ] || continue
         KERNEL=${kernel#*-}
         KERNEL_VERSION=${KERNEL%%-*}
         ABI=${KERNEL#*-}
@@ -208,11 +210,13 @@ case "$1" in
         ALTERNATIVE=$(readlink /etc/alternatives/#DEB_HOST_MULTIARCH#_gl_conf)
         if [ "$ALTERNATIVE" = "#LDSOCONF#" ]; then
             # Update initramfs so that the blacklist ends up in the initramfs
-            update-initramfs -u || true
+            if [ -x /usr/sbin/update-initramfs ]; then            
+                /usr/sbin/update-initramfs -u
 
-            if [ -n "$NEWEST_KERNEL" ] && [ ${CURRENT_KERNEL} != ${NEWEST_KERNEL} ]; then
-                # This can fail when dealing with a chroot see LP: #556653
-                update-initramfs -u -k $CURRENT_KERNEL || true
+                if [ -n "$NEWEST_KERNEL" ] && [ ${CURRENT_KERNEL} != ${NEWEST_KERNEL} ]; then
+                    # This can fail when dealing with a chroot see LP: #556653
+                    /usr/sbin/update-initramfs -u -k $CURRENT_KERNEL
+                fi
             fi
         fi
 
